<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Abcloudz.Application\Abcloudz.Application.csproj" />
    </ItemGroup>

</Project>
